API_V1_URI=/api/v1
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
#Externalize spring application properties
spring.config.import=optional:../../../../secrets.properties
## PostgresSQL
spring.datasource.name=sysreview_db
spring.datasource.host=localhost
spring.datasource.port=5432
spring.datasource.url=jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.name}
#drop n create table again, good for testing, comment this in production
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.security=TRACE
## Api URLs
#Ieee
api.ieee.url=https://ieeexploreapi.ieee.org/api/v1/search/articles
api.ieee.maxRecords=2000
#Scopus
api.scopus.url=https://api.elsevier.com/content/search/scopus
api.scopus.maxRecords=2000
#WOS
api.wos.url=https://wos-api.clarivate.com/api/woslite
api.wos.databaseId=WOS
api.wos.count=100
api.wos.source.url=https://www.webofscience.com/wos/woscc/full-record/
api.wos.maxRecords=2000
#Pubmed
api.pubmed.search.url=https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi
api.pubmed.search.db=pubmed
api.pubmed.search.sort=relevance
api.pubmed.search.rettype=docsum
api.pubmed.search.retmode=json
api.pubmed.search.retmax=2000
api.pubmed.fetch.url=https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi
api.pubmed.source.url=https://pubmed.ncbi.nlm.nih.gov/
# Logging settings
logging.level.org.springframework.web.client.RestTemplate=DEBUG
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type=trace

allowed.cors.origin.urls=http://localhost:3000
server.servlet.context-path=/sysreview
